
/* 
 * ANJIVO AI Listing Studio
 * File: lib/ai/listing-types.ts
 *
 * Shared types for:
 * - AI single listing
 * - AI bulk listing
 * - AI product images
 * - Product variants
 * - Seller/Admin review and confirmation
 */

export type ListingRole = "seller" | "admin";

export type ListingStatus =
  | "draft"
  | "processing"
  | "needs_review"
  | "pending_approval"
  | "approved"
  | "published"
  | "rejected"
  | "failed";

export type ImageView =
  | "front"
  | "back"
  | "left"
  | "right"
  | "detail"
  | "lifestyle";

export type ImageSource =
  | "original"
  | "enhanced"
  | "ai_generated";

export type ImageReviewStatus =
  | "pending"
  | "approved"
  | "rejected";

export interface AIProductImage {
  id: string;

  // URL of the image stored in Firebase Storage
  url: string;

  // Original uploaded image URL, if applicable
  originalUrl?: string;

  view: ImageView;
  source: ImageSource;

  altText: string;

  reviewStatus: ImageReviewStatus;

  isPrimary: boolean;

  // True when this image was generated by AI
  isAIGenerated: boolean;

  createdAt?: string;
}

export interface AIProductVariant {
  id: string;

  sku: string;

  // Example: Blue, Black, White
  color?: string;

  // Example: S, M, L, XL, XXL
  size?: string;

  // Optional additional variant attributes
  attributes: Record<string, string>;

  // Variant-specific images
  imageUrls: string[];

  // Seller must confirm actual stock
  stockQuantity: number | null;

  // Prices are stored as INR amounts
  sellingPrice: number | null;
  wholesalePrice: number | null;
  mrp: number | null;

  // True only after seller/admin confirms this variant
  isConfirmed: boolean;
}

export interface AIProductListing {
  id?: string;

  sellerId: string;

  createdBy: string;

  createdByRole: ListingRole;

  title: string;

  slug: string;

  description: string;

  shortDescription: string;

  brand: string;

  category: string;

  subcategory: string;

  productType: string;

  highlights: string[];

  searchKeywords: string[];

  attributes: Record<string, string>;

  images: AIProductImage[];

  variants: AIProductVariant[];

  // Main listing prices, if applicable
  sellingPrice: number | null;

  wholesalePrice: number | null;

  mrp: number | null;

  // Compliance details must be verified
  hsnCode: string;

  gstRate: number | null;

  countryOfOrigin: string;

  status: ListingStatus;

  aiGenerated: boolean;

  sellerConfirmed: boolean;

  adminApproved: boolean;

  createdAt?: string;

  updatedAt?: string;
}

export interface AIListingGenerateRequest {
  images: string[];

  sellerId: string;

  role: ListingRole;

  // Optional user-provided hints
  categoryHint?: string;

  brandHint?: string;

  productHint?: string;

  // Used to suggest relevant variant options
  variantHints?: {
    sizes?: string[];
    colors?: string[];
  };
}

export interface AIListingGenerateResponse {
  success: boolean;

  listing?: AIProductListing;

  error?: string;

  warnings?: string[];
}

export type BulkJobStatus =
  | "queued"
  | "processing"
  | "completed"
  | "completed_with_errors"
  | "failed";

export interface AIBulkListingItem {
  id: string;

  imageUrls: string[];

  listing?: AIProductListing;

  status: ListingStatus;

  error?: string;

  warnings?: string[];
}

export interface AIBulkListingJob {
  id: string;

  sellerId: string;

  createdBy: string;

  createdByRole: ListingRole;

  items: AIBulkListingItem[];

  totalProducts: number;

  completedProducts: number;

  failedProducts: number;

  status: BulkJobStatus;

  createdAt?: string;

  updatedAt?: string;
}

export interface AIListingConfirmation {
  listingId: string;

  confirmedBy: string;

  role: ListingRole;

  confirmedAt: string;

  confirmedFields: string[];

  approvedImageIds: string[];

  confirmedVariantIds: string[];

  submitForApproval: boolean;
}

export interface AIListingError {
  code: string;

  message: string;

  field?: string;

  retryable: boolean;
}
